name: Solidity CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1

      - name: Install Dependencies
        run: forge install

      - name: Compile Contracts
        run: forge build

      - name: Check if Tests Exist
        id: check-tests      # <--- Assign an ID here
        run: |
          if [ -z "$(find test -name '*.t.sol' 2>/dev/null)" ]; then
            echo "No tests found. Skipping..."
            echo "skip_tests=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip_tests=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

      - name: Run Tests
        if: steps.check-tests.outputs.skip_tests == 'false'
        run: forge test
